name: Ruby Client Tests

on:
  push:
    branches: [main]
    paths:
      - "fuckbase.rb"
      - "test_fuckbase.rb"
      - "run-client-tests.sh"
      - ".github/workflows/ruby-client-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "fuckbase.rb"
      - "test_fuckbase.rb"
      - "run-client-tests.sh"
      - ".github/workflows/ruby-client-tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.2"
          bundler-cache: false

      - name: Install dependencies
        run: |
          gem install msgpack base64 minitest

      - name: Start FuckBase server
        run: |
          docker compose up -d
          sleep 5 # Wait for server to start

      - name: Run tests
        run: |
          ruby test_fuckbase.rb

      - name: Stop FuckBase server
        run: |
          docker-compose down
